FROM debian:buster-slim
MAINTAINER Dr. Sathya Laufer <s.laufer@homegear.email>

RUN ln -s /config/homegear     /etc/homegear
RUN ln -s /share/homegear/lib /var/lib/homegear
RUN ln -s /share/homegear/log /var/log/homegear

EXPOSE 2001 2002 2003

